### ISSUE TITLE
Stack switcher looks strange in Preferences

### ISSUE THREAD

**Issue by cassidyjames** [dbhowell/peeq#44]
I'm not sure if this is because I have no connections yet, but the stack switcher in the preferences dialog looks unnecessary since there's only one child in the stack.

![Screenshot from 2021-08-19 21-05-06](https://user-images.githubusercontent.com/611168/130172966-7f73fa32-ae4b-4898-b4b5-ed563da3f1bb.png)

**Comment by dbhowell** [comment]
You are right, it's purely because there is only one child in the stack. 

I had planned to have more preferences, but probably shouldn't have added it like that.
